name: ghulk
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  image_picker:
  file_picker: ^3.0.1
  flutter_riverpod: ^1.0.3


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1

  http: ^0.13.4

  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  #firebase_storage: ^8.0.3
  firebase_storage: ^10.3.2
  provider: ^5.0.0
  uuid: ^3.0.6
  firebase_database: ^9.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

 
  assets:
    - images/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
